### ISSUE TITLE
API incorrect link

### ISSUE THREAD

**Issue by vpoonyak** [max180643/thai-gold-api#7]
Your README about API have incorrect link

This API is based on HTTPS requests and JSON responses. `https://api.chnwt.dev/thai-oil-api`

It should be `https://api.chnwt.dev/thai-gold-api`

**Comment by max180643** [comment]
Fixed with commit https://github.com/max180643/thai-gold-api/commit/c9e2f2dc862a99f2a6bb92e88a8364d4a48abbd3
